const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync(path.join(__dirname, '../site.js'), 'utf8');
const context = { document: { addEventListener() {} } };
vm.createContext(context);
vm.runInContext(source.replace('  document.addEventListener("DOMContentLoaded",',
  '  globalThis.engine = {parseBlocks, parseSrt, estimateTiming, resync, formatForPremiere};\n  document.addEventListener("DOMContentLoaded",'), context);
const e = context.engine;
const blocks = [['Replacement one'], ['Replacement two']];
const real = '1\n00:00:00,000 --> 00:00:00,040\nOne frame\n\n2\n00:00:00,040 --> 00:00:59,960\nLast';
const entries = e.parseSrt(real);
const times = rows => JSON.stringify(rows.map(({start, end}) => ({start, end})));
const normal = e.parseSrt(e.resync(blocks, entries));
assert.equal(times(normal), times(entries));
assert.equal(normal[0].text, 'Replacement one');
const before = JSON.stringify(entries);
e.resync(blocks, entries);
assert.equal(JSON.stringify(entries), before, 'Input must not be mutated');
const guarded = '0\n00:00:00,000 --> 00:00:00,040\n \n\n' + real + '\n\n3\n00:00:59,960 --> 00:01:00,000\n \n';
assert.equal(times(e.parseSrt(e.resync(blocks, e.parseSrt(guarded)))), times(entries));
const generated = e.parseSrt(e.estimateTiming(blocks, 5, 0));
assert.equal(generated.length, blocks.length);
assert.equal(generated[0].start, '00:00:00,000');
assert.ok(generated.every(row => row.text.trim()));
const roundTrip = e.parseSrt(e.resync(blocks, generated));
assert.equal(roundTrip.length, blocks.length);
assert.equal(times(roundTrip), times(generated));
assert.throws(() => e.resync([['one']], entries), /Block count mismatch/);
assert.throws(() => e.resync([], entries), /No text blocks/);
assert.throws(() => e.resync(blocks, []), /No valid entries/);
const formatted = e.formatForPremiere(e.resync(blocks, entries));
assert.ok(formatted.startsWith('\uFEFF'));
assert.ok(!/(?<!\r)\n/.test(formatted));
console.log('PASS: zero-start generation, unchanged reference timing, real 40ms caption preservation, legacy guards, input immutability, errors, BOM/CRLF.');
